### ISSUE TITLE
Doesn't work with .Net Core 2.1

### ISSUE THREAD

**Issue by Wolfeitz** [smartsheet-samples/csharp-read-write-sheet#1]
The Smartsheet Client doesn't seem to work with .Net Core 2.1

// Initialize client
SmartsheetClient ss = new SmartsheetBuilder().SetAccessToken(token).Build();

--------------------------------------------------------------------------

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  Source=smartsheet-csharp-sdk
  StackTrace:
   at Smartsheet.Api.Internal.Utility.Utility.GetOSFriendlyName()
   at Smartsheet.Api.Internal.SmartsheetImpl.GenerateUserAgent(String userAgent)
   at Smartsheet.Api.Internal.SmartsheetImpl.set_UserAgent(String value)
   at Smartsheet.Api.SmartsheetBuilder.Build()
   at ToolBox.BusinessClass.TccdApiRouting.AccessSmartSheet(String sheetId, String token) in C:\1\Projects\ToolBox\ToolBox\BusinessClass\TccdApiRouting.cs:line 67
   at ToolBox.Controllers.ReportingController.SmartSheetApprovals(String month) in C:\1\Projects\ToolBox\ToolBox\Controllers\ReportingController.cs:line 45
   at ToolBox.Controllers.ReportingController.Smart_ApprovalTracking() in C:\1\Projects\ToolBox\ToolBox\Controllers\ReportingController.cs:line 38
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

**Comment by timwellswa** [comment]
That is correct. The current C# SDK requires the .NET 4.5.2 (or above) framework.
